name: Release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16, 18]
        os: [ubuntu-latest]
    name: Test on Node ${{ matrix.node_version }} and ${{ matrix.os }}
    env: 
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock       
    steps:        
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          args: '--experimental-worker'
          
      - run: npm i npm@8 --global
      - run: npm i rollup --global
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build --if-present
      - run: npx semantic-release
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0
