name: Release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      #SSH_KEY:
      #  required: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    name: Test on Node ${{ matrix.node_version }} and ${{ matrix.os }}
    steps:
      - name: Setup SSH
      - run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
          ssh-add /home/runner/.ssh/github_actions        
        env: 
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock        
     
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          args: '--experimental-worker'
          
      - name: Install Modules | Run Build | Run Test      
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - run: npx semantic-release
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0
